name: Mage-OS Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { PHP_VERSION: php84-fpm, MAGEOS_VERSION: 2.0.0, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php84-fpm, MAGEOS_VERSION: 2.0.0, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 2.0.0, SAMPLE_DATA: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 2.0.0, SAMPLE_DATA: false }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.3.1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.3.1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.3.0, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.3.0, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.2.0, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.2.0, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.1.1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.1.1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.1.0, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.1.0, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.6, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.6, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.5, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.5, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.4, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.4, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.3, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.3, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.2, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php83-fpm, MAGEOS_VERSION: 1.0.2, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php82-fpm, MAGEOS_VERSION: 1.0.1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php82-fpm, MAGEOS_VERSION: 1.0.1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php82-fpm, MAGEOS_VERSION: 1.0.0, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php82-fpm, MAGEOS_VERSION: 1.0.0, SAMPLE_DATA: false, MAIN_VERSION: true }
    steps:
    - uses: actions/checkout@v5

    # Step 1: Build the docker image
    - name: Compute tag
      id: tags
      run: |
        tag="${{ matrix.cfg.PHP_VERSION }}-mage-os${{ matrix.cfg.MAGEOS_VERSION }}"
        main_tag="mage-os${{ matrix.cfg.MAGEOS_VERSION }}"

        if [[ "${{ matrix.cfg.SAMPLE_DATA }}" == "true" ]]; then
          tag="${tag}-sample-data"
          main_tag="${main_tag}-sample-data"
        fi

        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        echo "main_tag=$main_tag" >> "$GITHUB_OUTPUT"

    - name: Build the Docker image (without sample data)
      run:
        docker build mage-os -f mage-os/Dockerfile
        -t michielgerritsen/mage-os-community-edition:${{ steps.tags.outputs.tag }}
        -t ghcr.io/${{ github.repository }}/mage-os-community-edition:${{ steps.tags.outputs.tag }}
        -t ghcr.io/${{ github.repository }}/mage-os-community-edition:${{ steps.tags.outputs.main_tag }}
        --build-arg MAGEOS_VERSION=${{ matrix.cfg.MAGEOS_VERSION }}
        --build-arg PHP_VERSION=${{ matrix.cfg.PHP_VERSION }}
        --build-arg SAMPLE_DATA=${{ matrix.cfg.SAMPLE_DATA }}

    # Step 2: Test the docker image
    - name: Start the docker image
      run:
        docker run --memory=4G --detach --name mage-os-community-edition
        michielgerritsen/mage-os-community-edition:${{ steps.tags.outputs.tag }}

    - name: Copy the example test module
      run: |
        docker exec mage-os-community-edition mkdir -p /data/extensions/MichielGerritsen-ExampleTest/Test/Integration/
        docker cp Test/composer.json mage-os-community-edition:/data/extensions/MichielGerritsen-ExampleTest/
        docker cp Test/ExampleTest.php mage-os-community-edition:/data/extensions/MichielGerritsen-ExampleTest/Test/Integration/

    - name: Install the example test module
      run: docker exec mage-os-community-edition composer require michielgerritsen/exampletest:@dev

    - name: Enable developer mode
      run: docker exec mage-os-community-edition ./retry "bin/magento deploy:mode:set developer"

    - name: Run setup:di:compile
      run: docker exec mage-os-community-edition ./retry "php bin/magento setup:di:compile"

    - name: Install the example test module
      run: docker exec mage-os-community-edition composer require michielgerritsen/exampletest:@dev

    # Step 3: Upload the images to Docker Hub and ghcr.io.
    - name: Push the image to GitHub Container Registry
      if: github.ref == 'refs/heads/master'
      env:
        MAIN_VERSION: ${{ matrix.cfg.MAIN_VERSION }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}/mage-os-community-edition:${{ steps.tags.outputs.tag }}
        if [[ -n "${MAIN_VERSION}" ]]; then
          docker push ghcr.io/${{ github.repository }}/mage-os-community-edition:${{ steps.tags.outputs.main_tag }}
        fi

    - name: Push the image to Docker hub
      if: github.ref == 'refs/heads/master'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push michielgerritsen/mage-os-community-edition:${{ steps.tags.outputs.tag }}

    - name: Dump Docker logs files (on failure)
      if: failure()
      run: |
        mkdir failure-logs
        docker logs mage-os-community-edition > failure-logs/docker.log
        docker cp mage-os-community-edition:/data/var/log failure-logs/var/log

    - name: Upload failure artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failure-artifacts-${{ steps.tags.outputs.tag }}
        path: |
          failure-logs
