name: Magento 2.3 Community Edition Docker container build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p4, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p4, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p4, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p4, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p3, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p3, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p3, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p3, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p2, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p2, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: false }
          - { PHP_VERSION: php74-fpm, MAGENTO_VERSION: 2.3.7, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6-p1, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.6, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p2, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.5-p1, SAMPLE_DATA: true }
          # 2.3.4 is disabled as I get a lot of these errors after switchting to Composer 2:
          # Problem 1
          #  - Root composer.json requires zendframework/zend-barcode == 2.8.0.0 -> satisfiable by laminas/laminas-barcode[2.8.0].
          #  - laminas/laminas-barcode 2.8.0 requires laminas/laminas-zendframework-bridge ^1.0 -> found laminas/laminas-zendframework-bridge[1.0.0, ..., 1.8.0] but these were not loaded, likely because it conflicts with another require.
#          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: false }
#          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: true }
#          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: false }
#          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.4, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: false }
          - { PHP_VERSION: php73-fpm, MAGENTO_VERSION: 2.3.3, SAMPLE_DATA: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.2, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.2, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.1, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.1, SAMPLE_DATA: true, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.0, SAMPLE_DATA: false, MAIN_VERSION: true }
          - { PHP_VERSION: php72-fpm, MAGENTO_VERSION: 2.3.0, SAMPLE_DATA: true, MAIN_VERSION: true }
    steps:
    - uses: actions/checkout@v4

    # Step 1: Build the docker image
    - name: Compute tag
      id: tags
      run: |
        tag="${{ matrix.cfg.PHP_VERSION }}-magento${{ matrix.cfg.MAGENTO_VERSION }}"
        main_tag="magento${{ matrix.cfg.MAGENTO_VERSION }}"

        if [[ "${{ matrix.cfg.SAMPLE_DATA }}" == "true" ]]; then
          tag="${tag}-sample-data"
          main_tag="${main_tag}-sample-data"
        fi

        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        echo "main_tag=$main_tag" >> "$GITHUB_OUTPUT"

    - name: Build the Docker image
      run:
        docker build magento -f magento/Dockerfile-2.3
        -t michielgerritsen/magento-project-community-edition:${{ steps.tags.outputs.tag }}
        -t ghcr.io/${{ github.repository }}/magento-project-community-edition:${{ steps.tags.outputs.tag }}
        -t ghcr.io/${{ github.repository }}/magento-project-community-edition:${{ steps.tags.outputs.main_tag }}
        --build-arg MAGENTO_VERSION=${{ matrix.cfg.MAGENTO_VERSION }}
        --build-arg PHP_VERSION=${{ matrix.cfg.PHP_VERSION }}
        --build-arg SAMPLE_DATA=${{ matrix.cfg.SAMPLE_DATA }}

    # Step 2: Test the docker image
    - name: Start the docker image
      run:
        docker run --memory=4G --detach --name magento-project-community-edition
        michielgerritsen/magento-project-community-edition:${{ steps.tags.outputs.tag }}

    - name: Create the dummy test directory
      run: docker exec magento-project-community-edition mkdir -p /data/app/code/MichielGerritsen/Magento2ExtensionIntegrationTest/Test/Integration

    - name: Copy the example test module
      run: |
        docker exec magento-project-community-edition mkdir -p /data/extensions/MichielGerritsen-ExampleTest/Test/Integration/
        docker cp Test/composer.json magento-project-community-edition:/data/extensions/MichielGerritsen-ExampleTest/
        docker cp Test/ExampleTest.php magento-project-community-edition:/data/extensions/MichielGerritsen-ExampleTest/Test/Integration/

    - name: Install the example test module
      run: docker exec magento-project-community-edition composer require michielgerritsen/exampletest:@dev

    - name: Enable developer mode
      run: docker exec magento-project-community-edition ./retry "bin/magento deploy:mode:set developer"

    - name: Run setup:di:compile
      run: docker exec magento-project-community-edition ./retry "php bin/magento setup:di:compile"

    - name: Run the example test
      run: docker exec magento-project-community-edition bash -c "cd /data/dev/tests/integration/ && ../../../vendor/bin/phpunit /data/vendor/michielgerritsen/exampletest/Test/Integration/ExampleTest.php"

    # Step 3: Upload the images to Docker Hub and ghcr.io.
    - name: Push the image to GitHub Container Registry
      if: github.ref == 'refs/heads/master'
      env:
        MAIN_VERSION: ${{ matrix.cfg.MAIN_VERSION }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}/magento-project-community-edition:${{ steps.tags.outputs.tag }}
        if [[ -n "${MAIN_VERSION}" ]]; then
          docker push ghcr.io/${{ github.repository }}/magento-project-community-edition:${{ steps.tags.outputs.main_tag }}
        fi

    - name: Push the image to Docker hub
      if: github.ref == 'refs/heads/master'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push michielgerritsen/magento-project-community-edition:${{ steps.tags.outputs.tag }}

    - name: Dump Docker logs files (on failure)
      if: failure()
      run: |
        mkdir failure-logs
        docker logs magento-project-community-edition > failure-logs/docker.log
        docker cp magento-project-community-edition:/data/var/log failure-logs/var/log

    - name: Upload failure artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failure-artifacts-${{ steps.tags.outputs.tag }}
        path: |
          failure-logs
